cluster:
    name: dingo
exchange:
    host: 172.30.14.11
    port: 8765
server:
    coordinators: 172.30.14.11:32001,172.30.14.11:32002,172.30.14.11:32003
    user: user
    keyring: keyring
    resourceTag: 1
    mysqlPort: 3307
variable:
    autoIncrementCacheCount: 10000
    autoIncrementIncrement: 1
    autoIncrementOffset: 1
    enableTableLock: true
common:
    scheduledCoreThreads: 16
    lockCoreThreads: 0
    globalCoreThreads: 0
store:
    bufferSize: 67108864
    bufferNumber: 2
    fileSize: 67108864
    path: /home/server/work/dingo/localStore
security:
    ldap:
        ldapHost: ldap
        ldapPort: 389
        bindDN: cn=admin,dc=localdomain,dc=com
        password: 123456
        baseDN: dc=localdomain,dc=com
    cipher:
        keyPath: /home/server/work/dingo/conf/dingodb.jks
        keyPass: dingodb
        storePass: dingodb
        alias: dingodb
        issuer: dingo
